# Generated by Django 3.0.3 on 2020-04-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('unique_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('class_alloted', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CareTaker',
            fields=[
                ('unique_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('hostel_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClerkOffice',
            fields=[
                ('clerk_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('clerk_name', models.CharField(max_length=50)),
                ('department_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=25)),
                ('dept_hod', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PgBlock',
            fields=[
                ('employee_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('head_name', models.CharField(max_length=50)),
                ('head_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('urn', models.IntegerField(primary_key=True, serialize=False)),
                ('crn', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('FM_Name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('residence', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='./student_photo/')),
                ('class_calculated', models.CharField(max_length=50)),
            ],
        ),
    ]
