# Generated by Django 3.0.3 on 2020-03-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('unique_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('hostel_no', models.IntegerField()),
                ('date_and_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
