# Generated by Django 3.0.3 on 2020-04-13 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200412_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_form',
            fields=[
                ('unique_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('depo_name', models.CharField(max_length=25)),
                ('location_from', models.CharField(max_length=25)),
                ('location_to', models.CharField(max_length=25)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('old_pass_no', models.IntegerField()),
                ('urn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Student')),
            ],
        ),
    ]
