# Generated by Django 3.0.3 on 2020-04-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_application_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='level',
            field=models.CharField(default='caretaker', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application_form',
            name='status',
            field=models.CharField(default='Accepted', max_length=8),
        ),
    ]
