# Generated by Django 3.0.3 on 2020-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('unique_id', models.IntegerField()),
                ('hod_name', models.CharField(max_length=50)),
                ('clerk_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('date_and_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PgBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=50)),
                ('head_name', models.CharField(max_length=50)),
                ('head_id', models.IntegerField()),
                ('date_and_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
