# Generated by Django 3.0.3 on 2020-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200413_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_form',
            name='old_pass_no',
            field=models.CharField(max_length=12),
        ),
    ]
