# Generated by Django 3.0.3 on 2020-04-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200413_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(upload_to='./media/student_photo/'),
        ),
    ]
