# Generated by Django 3.0.3 on 2020-04-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200414_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hostel_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
