# Generated by Django 3.0.3 on 2020-04-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_student_hostel_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='description',
            field=models.CharField(default='Form filled by student', max_length=150),
            preserve_default=False,
        ),
    ]
