# Generated by Django 3.0.3 on 2020-04-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_application_form_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='hostel_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hnum', to='database.residence')),
            ],
        ),
    ]
