# Generated by Django 3.0.3 on 2020-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_hostel_num_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
            preserve_default=False,
        ),
    ]
