# Generated by Django 3.0.3 on 2020-04-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200423_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerkoffice',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Departments'),
        ),
    ]
