# Generated by Django 3.0.3 on 2020-04-24 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200423_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='datetime_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
