# Generated by Django 3.0.3 on 2020-04-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.IntegerField(),
        ),
    ]
