# Generated by Django 3.0.3 on 2020-04-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20200424_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.IntegerField(unique=True),
        ),
    ]
