# Generated by Django 3.0.3 on 2020-04-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20200424_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
