# Generated by Django 3.0.3 on 2020-04-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20200425_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
