# Generated by Django 3.0.3 on 2020-04-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_remove_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='abcd1234', max_length=8),
            preserve_default=False,
        ),
    ]
