# Generated by Django 3.0.3 on 2020-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_remove_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgblock',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='pgblock',
            name='head_id',
        ),
        migrations.AddField(
            model_name='pgblock',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
