# Generated by Django 3.0.3 on 2020-04-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_auto_20200425_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PgBlock',
        ),
    ]
