# Generated by Django 3.0.3 on 2020-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_pgblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyMCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
