# Generated by Django 3.0.3 on 2020-04-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_tinymce'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_message', models.CharField(max_length=250)),
                ('urn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='TinyMCE',
        ),
    ]
