# Generated by Django 3.0.3 on 2020-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_auto_20200426_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_complaint',
            name='status',
            field=models.CharField(default='Unprocessed', max_length=12),
            preserve_default=False,
        ),
    ]
