# Generated by Django 3.0.3 on 2020-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_student_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='department',
            field=models.CharField(default='CS', max_length=2),
            preserve_default=False,
        ),
    ]
